//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Technical_inspection
    {
        public int Id_inspection { get; set; }
        public Nullable<System.DateTime> Date_inspection { get; set; }
        public string Result { get; set; }
        public Nullable<int> Id_equipment { get; set; }
        public Nullable<bool> Done { get; set; }
        public string Status { get; set; }
        public string Employee_name { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
